Bacchus/Bacchus/Models/BacchusContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Bacchus.Models
{
    public class BacchusContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public BacchusContext() : base("name=BacchusContext")
        {
        }

        public System.Data.Entity.DbSet<Bacchus.Models.Products> Products { get; set; }

        public System.Data.Entity.DbSet<Bacchus.Models.Offers> Offers { get; set; }
    }
}

Bacchus/Bacchus/Models/Offers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Bacchus.Models
{
    public class Offers
    {

        public int Id { get; set; }
        [Display(Name = "Summa (EUR)")]
        [Required(ErrorMessage = "Summa on nõutav ja peab olema number")]
        [Range(1, 1000000, ErrorMessage = "Summa peab olema vahemikus 1 - 1000000.")]      
        public double Amount { get; set; }
        [Display(Name = "Eesnimi")]
        [Required(ErrorMessage = "Nimi on nõutav")]
        public string FirstName { get; set; }
        [Display(Name = "Perekonnanimi")]
        [Required(ErrorMessage = "Nimi on nõutav")]
        public string LastName { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? OfferDate { get; set; }
        public int ProductsId { get; set; }
        public Products Products { get; set; }


        [NotMapped]
        public string Name
        {
            get
            {
                if (FirstName != null && LastName != null)
                {
                    return String.Format("{0}{1}", FirstName, LastName);
                }
                else
                {
                    return String.Format("");
                }
            }


        }
    }
}

Bacchus/Bacchus/Models/Products.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bacchus.Models
{
    public class Products
    {
        public int Id { get; set; }
        public string ProductId { get; set; }
        [Display (Name = "Toode")]
        public string ProductName { get; set; }
        [Display(Name = "Kirjeldus")]
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public IEnumerable<SelectListItem> Category { get; set; }
        [Display(Name = "Pakkumise lõpp")]
        public DateTime? BiddingEndDate { get; set; }
        public ICollection<Offers> Offers { get; set; }
    }
}

Bacchus/Bacchus/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bacchus.Models;

namespace Bacchus.Controllers
{
    public class OffersController : Controller
    {
        private BacchusContext db = new BacchusContext();

        // GET: Offers
        public ActionResult Index()
        {

            var offers = db.Offers.Include(s => s.Products); 
            
            return View(offers);
        }

       
        // GET: Offers/Create
        public ActionResult Create(int? productsid)
        {
            
            if (productsid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View();

        }

        // POST: Products2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ProductsId,FirstName,LastName,Amount,OfferDate")] Offers offers)
        {

            if (ModelState.IsValid)

            {
                offers.OfferDate = DateTime.Now;
                db.Offers.Add(offers);
                db.SaveChanges();

                TempData["Salvestatud"] = "Sinu pakkumine on salvestatud";

                return View();
            }
            

            return RedirectToAction("Index", "Products");
        }

       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bacchus/Bacchus/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Bacchus.Models;

namespace Bacchus.Controllers
{
    public class ProductsController : Controller
    {
        private BacchusContext db = new BacchusContext();

        // GET: Products
        public ActionResult Index(string searchCategory, int? productsId)
        {
            List<Products> products = new List<Products>();

            HttpClient client = new HttpClient();
            var url = "http://uptime-auction-api.azurewebsites.net/api/Auction";
            var response = client.GetAsync(url).Result;

            var productIds = db.Products.Select(x => x.ProductId).ToList();

            if (response.IsSuccessStatusCode)
            {
                products = response.Content.ReadAsAsync <List<Products>>().Result;
                var productsToAdd = products.Where(x => !productIds.Contains(x.ProductId)).ToList();

                db.Products.AddRange(productsToAdd);
                db.SaveChanges();
            }

            ViewBag.searchCategory = new SelectList(products.Select(x => x.ProductCategory).Distinct().ToList(), String.Empty);
        
            if(!string.IsNullOrEmpty(searchCategory))
            {
                
                products = products.Where(s => s.ProductCategory.Contains(searchCategory)).ToList();
                
                return View(products.Where(p => p.BiddingEndDate > DateTime.Now.Subtract(TimeSpan.FromDays(1))));
                
            }
            
            return View(db.Products.ToList().Where(x => x.BiddingEndDate > DateTime.Now.Subtract(TimeSpan.FromDays(1))));
            
        }
        


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bacchus/Bacchus/Views/Offers/Create.cshtml
@model Bacchus.Models.Offers

@{
    ViewBag.Title = "Create";

}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



<div class="form-horizontal">
    <hr />
    <h4><span style='color:cadetblue;'>Tee oma pakkumine valitud tootele</span></h4>
    <hr />

    <span style='color:red;'>@TempData["Salvestatud"]</span>

    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Tagasi nimekirja", "Index", "Products")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bacchus/Bacchus/Views/Offers/Index.cshtml
@model IEnumerable<Bacchus.Models.Offers>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Products.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Products.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Bacchus/Bacchus/Views/Products/Create.cshtml
@model Bacchus.Models.Products

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BiddingEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BiddingEndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BiddingEndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Bacchus/Bacchus/Views/Products/Index.cshtml
@model IEnumerable<Bacchus.Models.Products>

@{
    ViewBag.Title = "Bacchus";


}
<hr />
<form action="/products/Index" method="get">
    <section>
        <div class="form-actions no-color">
            <h4><span style='color:cadetblue;'>Leia toode kategooria järgi</span></h4>
            @Html.DropDownList("searchCategory", null, "Vali kategooria", htmlAttributes: new { @class = "form-control" }) 
            <input type="submit" value="Näita" class="btn btn-default" />  
        </div>
    </section>
</form>
<hr />
<h4><span style='color:cadetblue;'>Aktiivsed oksjonid</span></h4>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BiddingEndDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BiddingEndDate)
            </td>
            <td>
                @Html.ActionLink("Paku", "Create", "Offers", new { productsId = item.Id, productsName = item.ProductName}, null)

            </td>
        </tr>
    }

</table>

Bacchus/Bacchus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Bacchus</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bacchus", "Index", "Products", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SeKer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>